### ISSUE TITLE
run instructions

### ISSUE THREAD

**Issue by paulschraven** [whyboris/JSON-i18n-Editor#10]
Hi @whyboris!

I like your project. Now I would like to run your project. There are no instructions.
Why Boris? ;)

All jokes aside, I was actually wondering how I should run this project locally or even deploy it somewhere, it's exactly what we need right now!

Best
Paul

**Comment by whyboris** [comment]
Sorry for the lack of specific instructions. I should add those to the `README` (though feel free to open a PR with your recommended instructions).

The app is all _angular_ and once you clone the repository and run `npm install` you should be able to `npm start` and have the app running locally.

When you want to build it for "production" you just `npm run build` and it generates maybe 10 static files that can be served from wherever - however you'd like. 

The tricky part is the "back end" which is supposed to serve up the `.json` files and save them when the app requests it. You can write your own back end code, but for convenience, just copy over the `php` folder to wherever you can serve php   from. PHP is awesome for simple things like this; I use [UwAmp](http://www.uwamp.com/en/) on Windows - super easy to work with. 

You'll need to change the URL in the app to point to where your server is: https://github.com/whyboris/JSON-i18n-Editor/blob/master/src/app/file.service.ts#L19

Please reach out if you have any questions! I'd be really happy to help 👍

**Comment by paulschraven** [comment]
Thanks so much for the detailed instructions Boris, I'll take a look!! :)

**Comment by whyboris** [comment]
Hey @paulschraven -- did you manage to get it to work? Let me know 🤝 😄

**Comment by paulschraven** [comment]
Hey Boris, we did, thanks for the explanation. We switched to using a paid alternative however, since we needed some of the comfort and features it provided :)

Best
Paul

**Comment by whyboris** [comment]
Thank you for giving my project a try 🤝
